name: treetok
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - arrow-cpp=16.1.0
  - attrs=23.1.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.2
  - certifi=2024.7.4
  - charset-normalizer=3.3.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.6.68
  - cuda-runtime=12.1.0
  - cuda-version=12.6
  - datasets=2.19.1
  - dill=0.3.8
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2024.3.1
  - gflags=2.2.2
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - huggingface_hub=0.24.6
  - icu=73.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libabseil=20240116.2
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.11.1.6
  - libcurand=10.3.7.68
  - libcurl=8.9.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.57.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libssh2=1.11.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.0.4
  - multiprocess=0.70.15
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.14
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.2.2
  - pillow=10.4.0
  - psutil=5.9.0
  - pyarrow=16.1.0
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - re2=2022.04.01
  - readline=8.2
  - regex=2024.7.24
  - requests=2.32.3
  - s2n=1.3.27
  - safetensors=0.4.4
  - setuptools=72.1.0
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - sympy=1.13.2
  - tbb=2021.8.0
  - tk=8.6.14
  - tokenizers=0.13.3
  - torchaudio=2.1.0
  - torchtriton=2.1.0
  - torchvision=0.16.0
  - tqdm=4.66.5
  - transformers=4.31.0
  - tzdata=2024a
  - urllib3=2.2.2
  - utf8proc=2.6.1
  - wheel=0.43.0
  - xxhash=0.8.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.8
    - asttokens==3.0.0
    - bitarray==2.9.2
    - cffi==1.17.1
    - click==8.1.8
    - colorama==0.4.6
    - cython==3.0.11
    - decorator==5.2.1
    - docker-pycreds==0.4.0
    - easydict==1.13
    - executing==2.2.0
    - fairseq==0.12.2
    - gitdb==4.0.11
    - gitpython==3.1.43
    - hydra-core==1.0.7
    - ipdb==0.13.13
    - ipython==9.4.0
    - ipython-pygments-lexers==1.1.1
    - jedi==0.19.2
    - joblib==1.4.2
    - lxml==5.3.0
    - matplotlib-inline==0.1.7
    - morfessor==2.0.6
    - omegaconf==2.0.6
    - parso==0.8.4
    - pexpect==4.9.0
    - pip==24.0
    - platformdirs==4.3.6
    - portalocker==2.10.1
    - prompt-toolkit==3.0.51
    - protobuf==5.29.2
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pycparser==2.22
    - pydantic==2.10.4
    - pydantic-core==2.27.2
    - pygments==2.19.2
    - sacrebleu==2.4.3
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - sentry-sdk==2.19.2
    - setproctitle==1.3.4
    - smmap==5.0.1
    - stack-data==0.6.3
    - tabulate==0.9.0
    - threadpoolctl==3.5.0
    - traitlets==5.14.3
    - typing-extensions==4.12.2
    - wandb==0.19.1
    - wcwidth==0.2.13