name: treetok
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - numpy
  - pandas
  - scipy
  - tqdm
  - pyyaml
  - transformers=4.31.0
  - datasets=2.19.1
  - pip:
      - wandb==0.19.1
      - scikit-learn==1.5.2
      - sacrebleu==2.4.3
      - portalocker==2.10.1